- name: install apache and php packages
  tags: apache,httpd,centos
  package:
    name: 
      - "{{ apache_package_name }}"
      - "{{ php_package_name }}"
    state: latest

- name: start httpd (centOS)
  tags: apache,httpd,centos
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: chnage e-mail address for admin
  tags: apache,centos,httpd
  lineinfile: 
    path: /etc/httpd/conf/httpd.conf 
    regexp: '^ServerAdmin'
    line: ServerAdmin someone@somewhere.com
  when: ansible_distribution == "CentOS"
  notify: restart_apache

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy: 
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0044
